# Generated by Django 4.2.6 on 2023-10-24 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('touristplace', '0002_touristplace_touristplaceimage_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('1', '1 Day'), ('2', '2 Days')], help_text='Select the package type (1 Day or 2 Days)', max_length=10, verbose_name='Package Type')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price for this package', max_digits=10, verbose_name='Price')),
                ('places_limit', models.IntegerField(choices=[(1, '3 Places (1 Day)'), (2, '6 Places (2 Days)')], help_text='Select the limit for tourist places', verbose_name='Places Limit')),
                ('places', models.ManyToManyField(help_text='Select tourist places for this package', to='touristplace.touristplace', verbose_name='Tourist Places')),
                ('state', models.ForeignKey(help_text='Choose the state for this package', on_delete=django.db.models.deletion.CASCADE, to='touristplace.state', verbose_name='State')),
            ],
        ),
    ]
