# Generated by Django 4.2.6 on 2023-10-24 19:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Select the booking date', verbose_name='Booking Date')),
                ('no_of_guests', models.IntegerField(help_text='Enter the number of guests (maximum 6)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Number of Guests')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='pending', max_length=20, null=True, verbose_name='Booking Status')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Payment Amount')),
                ('payment_method', models.CharField(blank=True, choices=[('online', 'Online Payment'), ('cash', 'Cash Payment')], max_length=50, verbose_name='Payment Method')),
                ('contact_email', models.EmailField(help_text='Enter the contact email address', max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=15, verbose_name='Contact Phone')),
                ('special_requests', models.TextField(blank=True, verbose_name='Special Requests')),
                ('package', models.ForeignKey(help_text='Select the package for the booking', on_delete=django.db.models.deletion.CASCADE, to='package.package', verbose_name='Package')),
                ('user', models.ForeignKey(help_text='Select the user making the booking', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['date'],
            },
        ),
    ]
