# Generated by Django 4.2.6 on 2023-10-24 07:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. Max length: 100 characters', max_length=100, unique=True, verbose_name='State Name')),
                ('description', models.TextField(help_text='Required', verbose_name='State Description')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='state_image')),
                ('alt', models.CharField(blank=True, help_text='Optional. Max length: 300 characters', max_length=300, null=True, verbose_name='Alt text')),
            ],
        ),
    ]
