# Generated by Django 4.2.6 on 2023-10-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristplace', '0002_touristplace_touristplaceimage_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='alt',
            field=models.CharField(blank=True, help_text='Optional. Max length: 300 characters', max_length=250, null=True, verbose_name='Alt text'),
        ),
    ]
