# Generated by Django 4.2.6 on 2023-10-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touristplace', '0003_alter_state_alt'),
    ]

    operations = [
    ]
